menu:
- {name: 'about', url: '/about'}
- {name: 'publications', url: '/publications'}
- {name: 'people', url: '/people'}
# - {name: 'projects', url: '/projects'}
# - {name: 'courses', url: '/courses'}
# - {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Dr. Geraldine Quek, PhD', title: 'Faculty Fellow', department: 'Architecture and Sustainable Design', institution: 'Singapore University of Technology and Design', institution_address: '8 Somapah Road, Singapore 487372', email: 'geraldine_quek@sutd.edu.sg', office: 'Building 1 Level 6', image: 'assets/img/GQ_Photo_BnW.jpg', url: 'geraldine-quek'}
- {name: 'Dr. Zheng Kai, PhD', title: 'Lecturer', department: 'Architecture and Sustainable Design', institution: 'Singapore University of Technology and Design', institution_address: '8 Somapah Road, Singapore 487372', email: 'kai_zheng@sutd.edu.sg', office: 'Building 1 Level 7', image: 'assets/img/asd-faculty-zheng-kai.jpeg', url: 'zheng-kai'}

collaborators:
- {name: 'Dr. Michal Gath-Morad, PhD', title: 'Postdoctoral Fellow', department: 'The Bartlett School of Architecture', institution: 'University College London', institution_address: '140 Hampstead Road, London, NW1 2BX, GB', image: 'assets/img/michal.jpeg'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/geraldinequek/'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Geraldine-Quek'}

contacts:
- {name: 'Dr. Geraldine Quek', title: 'Faculty Fellow', department: 'Architecture and Sustainable Design', institution: 'Singapore University of Technology and Design', institution_address: '8 Somapah Road, Singapore 487372', email: 'geraldine_quek@sutd.edu.sg', office: 'Building 1 Level 6', image: 'assets/img/GQ_Photo_BnW.jpg', url: 'geraldine-quek'}
